default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375
    hooks:
      - id: pyright
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
        files: ^(.*/)?pyproject.toml$
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.6.0
    hooks:
      - id: poetry-export
        name: poetry-export (prod)
        args:
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.txt"
      - id: poetry-export
        name: poetry-export (dev)
        args:
          - "--with"
          - "dev"
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.dev.txt"
